domain: manager.assets.ubuntu.com

image: prod-comms.docker-registry.canonical.com/manager.assets.ubuntu.com

env:
  - name: ASSET_SERVER_URL
    value: https://assets.ubuntu.com/v1/

  - name: ASSET_SERVER_TOKEN
    secretKeyRef:
      key: asset_server_token
      name: manager-assets-ubuntu-com

  - name: SENTRY_DSN
    value: https://7caf63ec2bb74f3b99e51cf7d9a3d75b@sentry.is.canonical.com//33

# Overrides for production
production:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";

# Overrides for staging
staging:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
